from . import utils
from . import cwa_product
from . import cwa_product_brands
from . import cwa_product_cblcode
from . import cwa_product_quality
from . import cwa_product_suppliers
from . import cwa_product_uom
from . import product_supplierinfo
from . import product_template
from . import cwa_vat_tax
from . import res_config_settings
